#! /bin/sh
J2TVLA_HOME=/home/me/Uni.lu/Master/MSemester2/Shape_Analysis/J2TVLA/j2tvla/
TVLA_HOME=/home/me/Uni.lu/Master/MSemester2/Shape_Analysis/TVLA/tvla-3.0alpha
J2TVLA_BUILD=/home/me/Uni.lu/Master/MSemester2/Shape_Analysis/J2TVLA/j2tvla/build
SOOT_CLASSES=/home/me/Uni.lu/Master/MSemester2/Shape_Analysis/J2TVLA/j2tvla/lib/soot-2.1.0/soot-2.1.0/classes
JASMIN_CLASSES=/home/me/Uni.lu/Master/MSemester2/Shape_Analysis/J2TVLA/j2tvla/lib/jasmin-sable-1.2.7
JAVA_PATH=/usr/lib/jvm/java-6-sun-1.6.0.26/jre/lib
JAVA_JCE=$JAVA_PATH/jce.jar


export CLASSPATH=$CLASSPATH:$J2TVLA_BUILD:$SOOT_CLASSES:$JASMIN_CLASSES:.:$JAVA_JCE

SOOT_ARGS="-app -w -keep-line-number -f jimple"

#java soot.Main
#java j2tvla.Main

path=$(dirname $1)
filename=$(basename $1)
filename=${filename%.*}

cd $path
java -Dj2tvla.home="$J2TVLA_HOME" j2tvla.Main $SOOT_ARGS $filename
